
---
version: "3"
services:

  opa:
    image: openpolicyagent/opa:0.13.0-dev-rootless
    ports:
      - 8181:8181
    command:
      - "run"
      - "--server"
      - "--config-file=/config.yaml"
      - "--log-level=info"
    volumes:
      - ./config.yaml:/config.yaml

    depends_on:
      - caddy

  caddy:
    build:
      context: caddy
    volumes:
      - ./bundles:/app
    ports:
      - 8080:8080
    environment:
      JWT_SECRET: 'qwertyuiopasdfghjklzxcvbnm123456'
