
---
version: "3"
services:

  opa:
    image: openpolicyagent/opa:0.13.0-dev-rootless
    ports:
      - 8181:8181
    command:
      - "run"
#     - "--ignore=.*"
      - "--server"
      - "/data/data.json"
      - "--log-level=info"
    volumes:
      - ./data:/data

